apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-nginx-deployment
spec:
  replicas: 2
  strategy:
    type: Recreate  
  selector:
    matchLabels:
      app: harness-nginx
  template:
    metadata:
      labels:
        app: harness-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80